name: pebrapp_console
description: Administrative tool for PEBRApp.
version: 1.0.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.3+4
  html: ^0.13.4+1
  http: ^0.12.0+2
  path: ^1.6.2

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.0
  flutter_test:
    sdk: flutter

# set the app launcher icon here, then to update the icon run
# `flutter packages pub run flutter_launcher_icons:main`
# https://pub.dartlang.org/packages/flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "logo_android.png"
  # image_path: "logo_ios.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
